### ISSUE TITLE
Season request not monitoring all episodes of latest season

### ISSUE THREAD

**Issue by Archmonger** [Ombi-app/Ombi#2953]
**Describe the bug**
Non-aired episodes are not marked as monitored when a season request is created.

**To Reproduce**
Do a season request on an ongoing show that isn't complete and watch as non-aired episodes are labeled as unmonitored .

**Expected behavior**
Season request should monitor all aired and non-aired episodes.

**Screenshots**
![image](https://user-images.githubusercontent.com/16909269/56846273-5275cd80-6882-11e9-8530-64a3f513d5cb.png)

**Logs (Logs directory where Ombi is located)**
N/A

**Desktop (please complete the following information):**

**Ombi Version (please complete the following information):**
 - Version: 3.0.4256
 - Media Server [e.g. Plex]: Plex

**Additional context**
N/A

**Comment by tidusjar** [comment]
Can you please provide an example show?

Also was the show already in sonarr previous to the request?

**Comment by Archmonger** [comment]
Was not in Sonarr prior to the request. I'm not entirely sure how to trigger it... but here's a few recent ones: 
Bless This Mess (2019), The Village (2019), Wise Man's Grandchild.

**Comment by tidusjar** [comment]
So just to be clear, 
When you say season request you mean the Select... and then select the latest season, or do you mean the latest season dropdown?

**Comment by Archmonger** [comment]
Pretty sure it's latest season but I'll ask all the users that requested.

**Comment by Archmonger** [comment]
Where the issue occurred, the users requested for "All Seasons". Is it possible this issue is caused when themoviedb is lagging behind on information on upcoming episodes in comparison to thetvdb?

**Comment by tidusjar** [comment]
I've actually just found the problem, it's a bug in Sonarr.

I'll raise it with the Sonarr team and reference the bug.

**Comment by tidusjar** [comment]
Sonarr bug raised: https://github.com/Sonarr/Sonarr/issues/3085

**Comment by Archmonger** [comment]
Just had this occur with an older show where every episode has already aired, 
![image](https://user-images.githubusercontent.com/16909269/57470964-fa09dd00-723e-11e9-8a19-8d1311cac45e.png)
![image](https://user-images.githubusercontent.com/16909269/57471020-16a61500-723f-11e9-8e3c-7f472fc3c940.png)

**Comment by tidusjar** [comment]
Steps to reproduce? Same questions as above, is it existing etc?

**Comment by Archmonger** [comment]
Seems like it was made via typical "all seasons" request on a non-existing series

**Comment by Archmonger** [comment]
This may not be directly related, but relates to monitoring logic. A request for season 31 of 48 Hours (1988) results in season 26-32 being monitored. I can open a separate issue if needed.
![image](https://user-images.githubusercontent.com/16909269/57588779-58002400-74ce-11e9-9305-35e15f587094.png)
![image](https://user-images.githubusercontent.com/16909269/57588781-68180380-74ce-11e9-9480-8a741877a59f.png)
![image](https://user-images.githubusercontent.com/16909269/57588782-70703e80-74ce-11e9-95cb-dfe20dced4cd.png)

**Comment by Archmonger** [comment]
Here's another sample that just occurred. All seasons request on an new series.
![image](https://user-images.githubusercontent.com/16909269/58064154-e0696f00-7b35-11e9-86a9-4b924629b43f.png)
![image](https://user-images.githubusercontent.com/16909269/58064165-e95a4080-7b35-11e9-9140-c88d32910cdf.png)

**Comment by cjmanca** [comment]
Anything being done about this? It happens a LOT where it just randomly doesn't monitor anything. I'm usually the one who's adding through Ombi, and definitely always hit the "All Seasons" option when doing it. But it just doesn't monitor them half the time.

Latest version of ombi and v3 Sonarr

**Comment by twanariens** [comment]
This should be fixed in the latest Ombi build (develop). Had to change some API calls

**Comment by mueslo** [comment]
@twanariens Seems like the bug persisted for longer than that. Just had it occur in Ombi 4.16.12 (2022/04/19) with a currently running season of a series, i.e. that has some episodes in the future. Re-running request processing only monitored those episodes which were already aired. 

Upgrading to Ombi 4.22.5 (latest release) fixed it (checked by request reprocess).
