### ISSUE TITLE
'Play on Jellyfin' button does not appear

### ISSUE THREAD

**Issue by Veexs** [Ombi-app/Ombi#4303]
**Describe the bug**
When you click on TV show or movie, it's only show as available in green but I can't find 'Play on Jellyfin' button.
Is it currently a bug with this version? 

Adress of jellyfin installation and API key correctly set in settings. 

**To Reproduce**
Go to any movie, or TV Show, and click everywhere, can't find Play on Jellyfin. 

**Expected behavior**
Normally as seen on different places, a button should be here to open item. 

I run last version of Jellyfin and Ombi.

**Comment by SamuelBartik** [comment]
This issue affects me as well. I have turned on Scan for availability for both radarr and sonarr settings,

**Comment by Veexs** [comment]
Sorry for the delay, 

Yes that option is turned on! 

Have you find a solution Samuel? 

Have a good night 

Envoyé de mon iPhone

**Comment by SamuelBartik** [comment]
Unfortunately, I couldn't find any working solutions. Let's wait for @tidusjar.

**Comment by tidusjar** [comment]
Ok, I think because you have those scans on, it's marking it as available so we are not checking jellyfin. This is a bug 😭

**Comment by SamuelBartik** [comment]
I have turned off the sonarr/radarr scans and then forced resync in jellyfin tab settings, and it still looks the same. Should it work by then?

**Comment by tidusjar** [comment]
You probably need to delete the ombiexternal.db and restart ombi then resync

**Comment by ozcrn** [comment]
Also running into the same issue - currently on 4.0.1468 using linuxserver/ombi

- Have confirmed Scan for Availability disabled for both Sonarr and Radarr
- Deleted OmbiExternal.db
- Restarted and did a full resync

Shows are available but still no play on Jellyfin button.

If I disable Sonarr and Radarr completely, I can see that the JellyfinContent table is still populated, but none of my content now show as available. Not sure if this is intended behaviour or not?

**Comment by tidusjar** [comment]
So with Shows, currently the requirements is that it needs to be fully available, but that doesn't make much sense so I'll change that

**Comment by tidusjar** [comment]
This has been fixed in the develop branch! 🎉 🎈

**Comment by neo-neo1** [comment]
> This has been fixed in the develop branch! 🎉 🎈

Not fixed, unfortunately.

Experiencing this same issue on 4.7.6 (docker develop branch). Brand new and fresh install.


<img width="1000" alt="ScreenShot 2021-12-09 at 6 34 59 AM" src="https://user-images.githubusercontent.com/6996362/145389693-e80a75c0-6037-4a30-b92f-4b545b30c20c.png">

**Comment by sephrat** [comment]
It works fine on my setup. This is most likely a configuration issue in Ombi. Please open a new issue or join us on Discord.

**Comment by neo-neo1** [comment]
> It works fine on my setup. This is most likely a configuration issue in Ombi. Please open a new issue or join us on Discord.

Brand new test install. I literally only setup Jellyin & Radarr. No idea how it’s a configuration issue.

**Comment by tidusjar** [comment]
@neo-neo1 can you please provide a bit more information and some screenshots?

If you have just set them up, has the content finished syncing in Ombi? Are you able to query the databases (not sure if you are using the default SQLite or MySQL setup) to check if Ombi has synced the content if I tell you what tables to interrogate?
