### ISSUE TITLE
Approve 4K Request Does Nothing

### ISSUE THREAD

**Issue by jaretclifton** [Ombi-app/Ombi#4509]
**Describe the bug**
Successfully enabled and configured the new 4K movie request function! Alas, all 4K Requests are required to be approved (no auto approve flag in user settings) but when clicking the Approve 4K button, nothing happens. If you click Approve Request, it follows the non-4K request flow.

**To Reproduce**
1. Go to any movie
2. Click on Request 4K
3. Go to Pending Requests for Movies
4. Click options for the movie and click Approve 4K Request

**Expected behavior**
The request is approved and sent to the appropriate 4K Radarr instance as configured

**Logs (Logs directory where Ombi is located)**
No log lines generated when clicking the Approve 4K Request button

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04

**Ombi Version (please complete the following information):**
 - Version 4.12.0
- Media Server Plex
- Database Type: MySQL

**Comment by computerguy951** [comment]
I noticed after setting up the radarr4k profile and root folder the setting does not seem to apply. Navigating away from the radarr4k settings and back shows blank settings even after submitting the profile and folder change. In testing 4k request I do not see my 4k root folder as a option to select. I'm wondering if this is why the same thing happens to me, 4k request goes in and then nowhere because the new root folder path is not present.

**Comment by jaretclifton** [comment]
The root folder "disappearing" thing is common to both 4k and non 4k configuration pages. If you save the settings, navigate away and then come back and press Load Profiles and Load Root Folders, they should auto populate with the correct values.

**Comment by computerguy951** [comment]
Ya you are correct it is doing it in both configurations. The difference being that even after saving the root folder on the 4k config It does not show up as a root folder option for user assignment or as a option when making a request

**Comment by jaretclifton** [comment]
Ah. Ok so different than what I'm seeing. Mine does indeed "stick".

**Comment by computerguy951** [comment]
I am also seeing the 4k request get stuck in pending and the approve 4k doing nothing also. I thought that I could get around this by selecting the correct root folder override when making the request which is when I realized my 4k root was not there as an option.

**Comment by jaretclifton** [comment]
Makes sense. I've tried requesting with root folder override vs not. Same situation where the request is stuck pending approval and the button doesn't do anything.

**Comment by tidusjar** [comment]
I expected a few hiccups with this. I’ll get onto it asap. 

Apologies guys

**Comment by tidusjar** [comment]
I’ve also missed the admin overrides for 4K. I thought I covered everything but I must have missed that.

**Comment by jaretclifton** [comment]
This feature is an AWESOME addition! Thank you for all the hard work on this project! Kudos!

**Comment by computerguy951** [comment]
No worries, I greatly appreciate all your hard work in continuing to develop awesome new features like this.

**Comment by tidusjar** [comment]
So the above commit should fix the problem when approving 4k, it did nothing.

If there are other issues, please can we raise a new bug, it can be hard to track when there's one issue on github with multiple issues being discussed.

Regarding the area's missed, I'll get around to doing them this week

**Comment by jaretclifton** [comment]
Looks like this fixed the bulk select -> bottom right pancake button -> approve 4k request. Looks like the individual request option button -> approve 4k still doesn't function. Thanks for the quick turn around!!!

**Comment by tidusjar** [comment]
This is not from the details page but the request grid?

**Comment by tidusjar** [comment]
Just pushed another update to fix that. I'm already aware that the request grid is not showing correctly (Movies that only have a 4k request is still showing as Pending approval). Will fix this later
