### ISSUE TITLE
StatusCode: BadGateway, Reason: Bad Gateway, RequestUri: https://ombinotifications.azurewebsites.net/api/MobileNotification

### ISSUE THREAD

**Issue by Kazz3r24** [Ombi-app/Ombi#5228]
### Summary

When trying to login via the QR code, the app does nothing. 

After manually logging in via OAUTH testing the mobile notifications result in the following log entries.

I've been beating my head against a wall thinking it was my reverse proxy settings, but they're confirmed to be good - so it's not me.

### Ombi Version

4.47.2

### What platform(s) does this occur on?

Linux

### What database are you using?

MySQL

### Relevant log output

```shell
2025-04-12 20:26:30.796 +00:00 [ERR] StatusCode: BadGateway, Reason: Bad Gateway, RequestUri: https://ombinotifications.azurewebsites.net/api/MobileNotification
2025-04-12 20:26:30.799 +00:00 [ERR] Error when sending mobile notification message, status code: BadGateway. Please raise an issue on Github, might be a problem with the notification service!
2025-04-12 20:26:39.839 +00:00 [ERR] StatusCode: BadGateway, Reason: Bad Gateway, RequestUri: https://ombinotifications.azurewebsites.net/api/MobileNotification
2025-04-12 20:26:39.839 +00:00 [ERR] StatusCode: BadGateway, Reason: Bad Gateway, RequestUri: https://ombinotifications.azurewebsites.net/api/MobileNotification
2025-04-12 20:26:39.840 +00:00 [ERR] Error when sending mobile notification message, status code: BadGateway. Please raise an issue on Github, might be a problem with the notification service!
2025-04-12 20:26:39.840 +00:00 [ERR] Error when sending mobile notification message, status code: BadGateway. Please raise an issue on Github, might be a problem with the notification service!
2025-04-12 20:27:18.171 +00:00 [ERR] StatusCode: BadGateway, Reason: Bad Gateway, RequestUri: https://ombinotifications.azurewebsites.net/api/MobileNotification
2025-04-12 20:27:18.172 +00:00 [ERR] Error when sending mobile notification message, status code: BadGateway. Please raise an issue on Github, might be a problem with the notification service!
2025-04-12 20:27:44.228 +00:00 [ERR] StatusCode: BadGateway, Reason: Bad Gateway, RequestUri: https://ombinotifications.azurewebsites.net/api/MobileNotification
2025-04-12 20:27:44.229 +00:00 [ERR] Error when sending mobile notification message, status code: BadGateway. Please raise an issue on Github, might be a problem with the notification service!
2025-04-12 20:27:44.239 +00:00 [ERR] StatusCode: BadGateway, Reason: Bad Gateway, RequestUri: https://ombinotifications.azurewebsites.net/api/MobileNotification
2025-04-12 20:27:44.239 +00:00 [ERR] Error when sending mobile notification message, status code: BadGateway. Please raise an issue on Github, might be a problem with the notification service!
```

**Comment by Jandalslap** [comment]
Same here. QR code wont scan. Can log in manually. Mobile notifications not working.

**Comment by tidusjar** [comment]
I’ll take a look

**Comment by tidusjar** [comment]
Should all be fixed now

**Comment by Jandalslap** [comment]
Just like that. Legend!

**Comment by Kazz3r24** [comment]
Unfortunately after enabling debugging I can't open the log from today anymore, but the issue with being unable to login via QR code in the app is still present for me, so the device isn't registered and I still can't receive notifications.

I've gone over my reverse proxy multiple times, when I use a standard QR code scanner the URL looks fine, https://mydomain.xyz/then the token but when I tried to access it via a browser it's just a white page, I assume it's something to do with my reverse proxy but this used to work before, so I'm not sure.

Is there something I can provide in order to get assistance with troubleshooting?

**Comment by tidusjar** [comment]
Regarding the qr code, that’s very hard for me to help with because it’s down to everyone’s setup. I’m by far not an expert with reverse proxies.

**Comment by Jandalslap** [comment]
Just FYI last time I tried  to use it I couldn’t get tonscan anything. I think thats what the OP means. It wont scan a QR code at all. Manual entry only.

**Comment by Kazz3r24** [comment]
Unfortunately manual entry signs me into Ombi in the app, but it doesn't register the device on the server and thus still no mobile notifications.

I know it used to work fine, but then I switched to Overseerr for a while but missed some of the features in Ombi, so I tried switching back and this is the result. I wouldn't mind it so much if I didn't pay of the Ombi app (80% sure it's a paid app).

I mainly switched back because I like the landing page of Ombi and some other features, and Overseerr hasn't seen an update in over a year (I know no one here cares about Overseerr). Unfortunately I'll have to switch back if I can't get this working - I'm not home much and I get requests and issues etc I need to be able to triage remotely.

Thank you for your efforts though! At least it's working for some.

**Comment by tidusjar** [comment]
It’s on my list to look why some peoples notifications are not registering

**Comment by Jandalslap** [comment]
Just FYI when I re install the app for any reason, I’ve found that I have to get the manual address correct the first time. If I make a typo for example and it fails, I need to delete the app and start again. Subsequent attempts even with corrected url will not connect.

**Comment by tidusjar** [comment]
this was resolved
